const NEW_PLAYERS = [
  // Hércules
  { name: "Tote", teams: ["Real Madrid", "Benfica", "Malaga", "Hércules"], aliases: ["tote"] },
  { name: "Javier Farinós", teams: ["Valencia", "Inter Milan", "Villarreal", "Hércules"], aliases: ["farinos"] },
  { name: "Noé Pamarot", teams: ["Nice", "Portsmouth", "Tottenham", "Hércules"], aliases: ["pamarot"] },
  { name: "Juan Calatayud", teams: ["Malaga", "Racing Santander", "Mallorca", "Hércules"], aliases: ["calatayud"] },
  { name: "Abraham Paz", teams: ["Cadiz", "Hércules"], aliases: ["abraham paz"] },

  // Real Murcia
  { name: "Fabian Carini", teams: ["Juventus", "Inter Milan", "Real Murcia"], aliases: ["carini"] },
  { name: "Alvaro Mejia", teams: ["Real Madrid", "Real Murcia"], aliases: ["mejia"] },
  { name: "Enrique de Lucas", teams: ["Espanyol", "Chelsea", "Alaves", "Real Murcia", "Celta Vigo"], aliases: ["de lucas"] },
  { name: "Jose Maria Movilla", teams: ["Atletico Madrid", "Zaragoza", "Rayo Vallecano", "Real Murcia"], aliases: ["movilla"] },
  { name: "Pablo Garcia", teams: ["Osasuna", "Real Madrid", "AC Milan", "Real Murcia"], aliases: ["pablo garcia"] },
  { name: "Ivan Alonso", teams: ["Alaves", "Espanyol", "Real Murcia"], aliases: ["ivan alonso"] },
  { name: "Henok Goitom", teams: ["Udinese", "Almeria", "Real Valladolid", "Real Murcia"], aliases: ["goitom"] },
  { name: "Fernando Baiano", teams: ["Celta Vigo", "Malaga", "Real Murcia"], aliases: ["baiano"] },
  { name: "Cesar Arzo", teams: ["Villarreal", "Recreativo", "Real Valladolid", "Real Murcia"], aliases: ["arzo"] },
  { name: "Antonio Notario", teams: ["Sevilla", "Celta Vigo", "Albacete", "Real Murcia"], aliases: ["notario"] },

  // Recreativo
  { name: "Florent Sinama-Pongolle", teams: ["Liverpool", "Atletico Madrid", "Sporting CP", "Recreativo"], aliases: ["sinama pongolle"] },
  { name: "Beto", teams: ["Sporting CP", "Recreativo"], aliases: ["beto server"] },
  { name: "Javi Guerrero", teams: ["Racing Santander", "Celta Vigo", "Las Palmas", "Recreativo"], aliases: ["javi guerrero"] },
  { name: "Jesus Vazquez", teams: ["Tenerife", "Deportivo La Coruña", "Recreativo"], aliases: ["jesus vazquez"] },
  { name: "Aitor Tornavaca", teams: ["Sporting de Gijón", "Leganes", "Recreativo"], aliases: ["aitor"] },
  { name: "Mario", teams: ["Real Valladolid", "Getafe", "Real Betis", "Recreativo"], aliases: ["mario alvarez"] },
  { name: "Lopez Vallejo", teams: ["Osasuna", "Villarreal", "Zaragoza", "Recreativo"], aliases: ["lopez vallejo"] },

  // Numancia
  { name: "Jose Javier Barkero", teams: ["Real Sociedad", "Levante", "Zaragoza", "Numancia"], aliases: ["barkero"] },
  { name: "Txomin Nagore", teams: ["Osasuna", "Athletic Bilbao", "Atletico Madrid", "Numancia"], aliases: ["nagore"] },
  { name: "Juan Pablo", teams: ["Sporting de Gijón", "Alaves", "Numancia"], aliases: ["juan pablo"] },
  { name: "Domingo Cisma", teams: ["Almeria", "Racing Santander", "Atletico Madrid", "Numancia"], aliases: ["cisma"] },
  { name: "Dimas Delgado", teams: ["Barcelona", "Recreativo", "Numancia"], aliases: ["dimas"] },
  { name: "Juan Carlos Moreno", teams: ["Barcelona", "Alaves", "Numancia"], aliases: ["juan carlos moreno"] },
  { name: "Gorka Brit", teams: ["Real Sociedad", "Numancia"], aliases: ["gorka brit"] },
  { name: "Asier Goiria", teams: ["Numancia"], aliases: ["goiria"] },

  // Albacete
  { name: "Manuel Almunia", teams: ["Arsenal", "Albacete"], aliases: ["almunia"] },
  { name: "Carlos Roa", teams: ["Mallorca", "Albacete"], aliases: ["roa"] },
  { name: "Fernando Navarro", teams: ["Barcelona", "Mallorca", "Sevilla", "Albacete"], aliases: ["fernando navarro"] },
  { name: "Mark Gonzalez", teams: ["Liverpool", "Real Sociedad", "Real Betis", "Albacete"], aliases: ["mark gonzalez"] },
  { name: "Antonio Pacheco", teams: ["Peñarol", "Inter Milan", "Espanyol", "Albacete"], aliases: ["pacheco"] },
  { name: "Jaime Sanchez", teams: ["Real Madrid", "Racing Santander", "Deportivo La Coruña", "Albacete"], aliases: ["jaime"] },
  { name: "Pablo Redondo", teams: ["Valencia", "Getafe", "Albacete"], aliases: ["redondo"] },

  // Tenerife
  { name: "Nino", teams: ["Elche", "Osasuna", "Tenerife"], aliases: ["nino"] },
  { name: "Alejandro Alfaro", teams: ["Sevilla", "Mallorca", "Real Valladolid", "Tenerife"], aliases: ["alfaro"] },
  { name: "Sergio Aragoneses", teams: ["Atletico Madrid", "Getafe", "Hércules", "Tenerife"], aliases: ["aragoneses"] },
  { name: "Mikel Alonso", teams: ["Real Sociedad", "Tenerife"], aliases: ["mikel alonso"] },
  { name: "Ricardo Leon", teams: ["Sporting de Gijón", "Tenerife"], aliases: ["ricardo leon"] },
  { name: "Juanlu Hens", teams: ["Valencia", "Granada", "Girona", "Tenerife"], aliases: ["juanlu hens"] },
  { name: "Marc Bertran", teams: ["Espanyol", "Osasuna", "Leganes", "Tenerife"], aliases: ["marc bertran"] },
  { name: "Daniel Kome", teams: ["Getafe", "Mallorca", "Real Valladolid", "Tenerife"], aliases: ["kome"] },

  // Racing Santander
  { name: "Toño", teams: ["Racing Santander", "Granada", "Rayo Vallecano", "Elche"], aliases: ["tono"] },
  { name: "Gonzalo Colsa", teams: ["Atletico Madrid", "Real Valladolid", "Mallorca", "Racing Santander"], aliases: ["colsa"] },
  { name: "Pinillos", teams: ["Levante", "Racing Santander"], aliases: ["pinillos"] },
  { name: "Oscar Serrano", teams: ["Espanyol", "Racing Santander", "Levante"], aliases: ["oscar serrano"] },
  { name: "Mohammed Tchite", teams: ["Racing Santander"], aliases: ["tchite"] },
  { name: "Nikola Zigic", teams: ["Valencia", "Racing Santander"], aliases: ["zigic"] },
  { name: "Christian Fernandez", teams: ["Racing Santander", "Almeria", "Real Oviedo"], aliases: ["christian fernandez"] },
  { name: "Mehdi Lacen", teams: ["Alaves", "Racing Santander", "Getafe", "Malaga"], aliases: ["lacen"] },

  // Almeria
  { name: "Albert Crusat", teams: ["Espanyol", "Almeria"], aliases: ["crusat"] },
  { name: "Ortiz Bernal", teams: ["Almeria"], aliases: ["ortiz bernal"] },
  { name: "Kalu Uche", teams: ["Espanyol", "Levante", "Almeria"], aliases: ["kalu uche"] },
  { name: "Juanma Ortiz", teams: ["Atletico Madrid", "Osasuna", "Almeria"], aliases: ["juanma ortiz"] },
  { name: "Hernan Pellerano", teams: ["Almeria"], aliases: ["pellerano"] },
  { name: "Miguel Angel Corona", teams: ["Real Madrid", "Zaragoza", "Almeria"], aliases: ["corona"] },
  { name: "Esteban", teams: ["Real Oviedo", "Atletico Madrid", "Sevilla", "Celta Vigo", "Almeria"], aliases: ["esteban"] },

  // Sporting de Gijón
  { name: "Alberto Lora", teams: ["Sporting de Gijón"], aliases: ["lora"] },
  { name: "Gregory Arnolin", teams: ["Sporting de Gijón"], aliases: ["gregory"] },
  { name: "Roberto Canella", teams: ["Sporting de Gijón", "Deportivo La Coruña", "Lugo"], aliases: ["canella"] },
  { name: "Carmelo", teams: ["Las Palmas", "Levante", "Sporting de Gijón"], aliases: ["carmelo"] },
  { name: "Miguel de las Cuevas", teams: ["Atletico Madrid", "Osasuna", "Sporting de Gijón"], aliases: ["de las cuevas"] },
  { name: "Mate Bilic", teams: ["Zaragoza", "Sporting de Gijón"], aliases: ["bilic"] },

  // Cadiz
  { name: "Armando Riveiro", teams: ["Cadiz", "Athletic Bilbao"], aliases: ["armando"] },
  { name: "Enrique", teams: ["Cadiz"], aliases: ["enrique"] },
  { name: "Nenad Mirosavljevic", teams: ["Cadiz"], aliases: ["mirosavljevic"] },
  { name: "Lucas Lobos", teams: ["Cadiz"], aliases: ["lobos"] },
  { name: "Matias Pavoni", teams: ["Cadiz"], aliases: ["pavoni"] },
  { name: "Jose Julian de la Cuesta", teams: ["Cadiz", "Real Valladolid"], aliases: ["de la cuesta"] },
  { name: "Andres Fleurquin", teams: ["Cadiz", "Villarreal"], aliases: ["fleurquin"] }
];

const NEW_PROFILES = {
  "tote": { countryCode: "es", position: "MC" },
  "farinos": { countryCode: "es", position: "MC" },
  "pamarot": { countryCode: "fr", position: "DFC" },
  "calatayud": { countryCode: "es", position: "POR" },
  "abraham paz": { countryCode: "es", position: "DFC" },
  "carini": { countryCode: "uy", position: "POR" },
  "mejia": { countryCode: "es", position: "DFC" },
  "de lucas": { countryCode: "es", position: "MC" },
  "movilla": { countryCode: "es", position: "MC" },
  "pablo garcia": { countryCode: "uy", position: "MC" },
  "ivan alonso": { countryCode: "uy", position: "DC" },
  "goitom": { countryCode: "se", position: "DC" },
  "baiano": { countryCode: "br", position: "DC" },
  "arzo": { countryCode: "es", position: "DFC" },
  "notario": { countryCode: "es", position: "POR" },
  "sinama pongolle": { countryCode: "fr", position: "DC" },
  "beto server": { countryCode: "pt", position: "DFC" },
  "javi guerrero": { countryCode: "es", position: "DC" },
  "jesus vazquez": { countryCode: "es", position: "MC" },
  "aitor": { countryCode: "es", position: "MC" },
  "mario alvarez": { countryCode: "es", position: "DFC" },
  "lopez vallejo": { countryCode: "es", position: "POR" },
  "nagore": { countryCode: "es", position: "MC" },
  "juan pablo": { countryCode: "es", position: "POR" },
  "cisma": { countryCode: "es", position: "LI" },
  "dimas": { countryCode: "es", position: "MC" },
  "juan carlos moreno": { countryCode: "es", position: "MC" },
  "gorka brit": { countryCode: "es", position: "DC" },
  "goiria": { countryCode: "es", position: "DC" },
  "almunia": { countryCode: "es", position: "POR" },
  "roa": { countryCode: "ar", position: "POR" },
  "fernando navarro": { countryCode: "es", position: "LI" },
  "mark gonzalez": { countryCode: "cl", position: "EI" },
  "pacheco": { countryCode: "uy", position: "DC" },
  "jaime": { countryCode: "es", position: "MC" },
  "redondo": { countryCode: "es", position: "MC" },
  "nino": { countryCode: "es", position: "DC" },
  "alfaro": { countryCode: "es", position: "DC" },
  "aragoneses": { countryCode: "es", position: "POR" },
  "mikel alonso": { countryCode: "es", position: "MC" },
  "ricardo leon": { countryCode: "es", position: "MC" },
  "juanlu hens": { countryCode: "es", position: "MC" },
  "marc bertran": { countryCode: "es", position: "LD" },
  "kome": { countryCode: "cm", position: "MC" },
  "tono": { countryCode: "es", position: "POR" },
  "colsa": { countryCode: "es", position: "MC" },
  "pinillos": { countryCode: "es", position: "LD" },
  "oscar serrano": { countryCode: "es", position: "EI" },
  "tchite": { countryCode: "bi", position: "DC" },
  "zigic": { countryCode: "rs", position: "DC" },
  "christian fernandez": { countryCode: "es", position: "LI" },
  "lacen": { countryCode: "dz", position: "MCD" },
  "crusat": { countryCode: "es", position: "EI" },
  "ortiz bernal": { countryCode: "es", position: "ED" },
  "kalu uche": { countryCode: "ng", position: "DC" },
  "juanma ortiz": { countryCode: "es", position: "LD" },
  "pellerano": { countryCode: "ar", position: "DFC" },
  "corona": { countryCode: "es", position: "MC" },
  "esteban": { countryCode: "es", position: "POR" },
  "lora": { countryCode: "es", position: "LD" },
  "gregory": { countryCode: "fr", position: "DFC" },
  "canella": { countryCode: "es", position: "LI" },
  "carmelo": { countryCode: "es", position: "MCO" },
  "de las cuevas": { countryCode: "es", position: "MCO" },
  "bilic": { countryCode: "hr", position: "DC" },
  "armando": { countryCode: "es", position: "POR" },
  "enrique": { countryCode: "es", position: "ED" },
  "mirosavljevic": { countryCode: "rs", position: "DC" },
  "lobos": { countryCode: "ar", position: "MCO" },
  "pavoni": { countryCode: "ar", position: "MCO" },
  "de la cuesta": { countryCode: "co", position: "DFC" },
  "fleurquin": { countryCode: "uy", position: "MCD" }
};
